title: Dadhood
description: Welcome to Dadhood, a site dedicated to lifting families, sharing inspiration, and sharing insights from the perspective of new parents.
show_downloads: true

baseurl: "/cayman-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://dsteed77.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "David and Danielle Steed"
image: /thumbnail-jumbo.png
twitter:
  username: dsteed77
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id: 1798910940422432 # cayman-blog
  #authors: DavidSteed
#  admins:
